# Generated by Django 2.1.3 on 2018-12-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('punteggio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id_test', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('extraversion', models.FloatField(default=0)),
                ('coscientiousness', models.FloatField(default=0)),
                ('agreeableness', models.FloatField(default=0)),
                ('openness', models.FloatField(default=0)),
                ('neuroticism', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleQuestions',
            fields=[
                ('id_test', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=3)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Question'),
        ),
    ]
