# Generated by Django 2.1.3 on 2018-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraversion', models.FloatField(default=0)),
                ('coscientiousness', models.FloatField(default=0)),
                ('agreeableness', models.FloatField(default=0)),
                ('openness', models.FloatField(default=0)),
                ('neuroticism', models.FloatField(default=0)),
            ],
        ),
    ]
