# Generated by Django 2.1.3 on 2018-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AddField(
            model_name='peoplequestions',
            name='cat',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AddField(
            model_name='peoplequestions',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peoplequestions',
            name='id_test',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='peoplequestions',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
