# Generated by Django 2.1.3 on 2019-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_question_people_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtherPeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('born', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=100)),
                ('level_school', models.CharField(max_length=100)),
                ('employment', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
