# Generated by Django 2.1.3 on 2018-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181217_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='oggetto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
