# Generated by Django 2.1.3 on 2019-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190124_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtherpeopleinfo',
            name='date_of_birth',
            field=models.CharField(max_length=30),
        ),
    ]
