# Generated by Django 2.1.5 on 2019-01-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190130_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email_comma_separated',
            new_name='email_line_by_line',
        ),
    ]
